export const API_URL = `https://maeramad-office-server.herokuapp.com/api`

export const secretKey = 'mySecretKey'

export const RELOAD_MATERIAL_DATA = 'RELOAD_MATERIAL_DATA'

export const LOADING_CATEGORY = "LOADING_CATEGORY"
export const GET_CATEGORY = "GET_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"

export const LOADING_MATERIAL = "LOADING_MATERIAL"
export const GET_MATERIAL_COMPLETED = "GET_MATERIAL_COMPLETED"
export const CREATE_MATERIAL = "CREATE_MATERIAL"
export const UPDATE_MATERIAL = "UPDATE_MATERIAL"
export const UPDATE_MATERIAL_STATUS = "UPDATE_MATERIAL_STATUS"
export const REMOVE_MATERIAL = "REMOVE_MATERIAL"

export const LOADING_DURABLE_CATEGORY = "LOADING_DURABLE_CATEGORY"
export const GET_DURABLE_CATEGORY = "GET_DURABLE_CATEGORY"
export const CREATE_DURABLE_CATEGORY = "CREATE_DURABLE_CATEGORY"
export const UPDATE_DURABLE_CATEGORY = "UPDATE_DURABLE_CATEGORY"
export const REMOVE_DURABLE_CATEGORY = "REMOVE_DURABLE_CATEGORY"

export const LOADING_DURABLE = "LOADING_DURABLE"
export const GET_DURABLE = "GET_DURABLE"
export const CREATE_DURABLE = "CREATE_DURABLE"
export const UPDATE_DURABLE = "UPDATE_DURABLE"
export const REMOVE_DURABLE = "REMOVE_DURABLE"

export const LOADING_REGISTERED_DURABLE = "LOADING_REGISTERED_DURABLE"
export const GET_REGISTERED_DURABLE = "GET_REGISTERED_DURABLE"
export const CREATE_REGISTER_DURABLE = "CREATE_REGISTER_DURABLE"
export const UPDATE_REGISTER_DURABLE = "UPDATE_REGISTER_DURABLE"
export const REMOVE_REGISTER_DURABLE = "REMOVE_REGISTER_DURABLE"

export const LOADING_OFFICE = "LOADING_OFFICE"
export const GET_OFFICE_COMPLETED = "GET_OFFICE_COMPLETED"
export const CREATE_OFFICE = "CREATE_OFFICE"
export const UPDATE_OFFICE = "UPDATE_OFFICE"
export const REMOVE_OFFICE = "REMOVE_OFFICE"

// material receive types
export const LOADING_MATERIAL_RECEIVE = "LOADING_MATERIAL_RECEIVE"
export const GET_MATERIAL_RECEIVE = "GET_MATERIAL_RECEIVE"
export const CREATE_MATERIAL_RECEIVE = "CREATE_MATERIAL_RECEIVE"
export const UPDATE_MATERIAL_RECEIVE = "UPDATE_MATERIAL_RECEIVE"
export const DELETE_MATERIAL_RECEIVE = "DELETE_MATERIAL_RECEIVE"
/// material order types
export const LOADING_MATERIAL_ORDER = "LOADING_MATERIAL_ORDER"
export const GET_MATERIAL_ORDER = "GET_MATERIAL_ORDER"
export const CREATE_MATERIAL_ORDER = "CREATE_MATERIAL_ORDER"
export const UPDATE_MATERIAL_ORDER = "UPDATE_MATERIAL_ORDER"
export const DELETE_MATERIAL_ORDER = "DELETE_ORDER_MATERIAL"
export const UPDATE_ORDER_STATUS_BY_ID = "UPDATE_ORDER_STATUS_BY_ID"
export const UPDATE_ORDER_STATUS_BY_ID_AND_PAID = "UPDATE_ORDER_STATUS_BY_ID_AND_PAID"


export const LOADING_DEPARTMENT = "LOADING_DEPARTMENT"
export const GET_DEPARTMENT_COMPLETED = "GET_DEPARTMENT_COMPLETED"
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT"
export const ONCLICK_UPDATE_DEPARTMENT = 'ONCLICK_UPDATE_DEPARTMENT'
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT"
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"

// personnel reducertypes
export const LOADING_PERSONNEL = "LOADING_PERSONNEL"
export const GET_PERSONNEL_COMPLETED = "GET_PERSONNEL_COMPLETED"
export const CREATE_PERSONNEL = "CREATE_PERSONNEL"
export const UPDATE_PERSONNEL = "UPDATE_PERSONNEL"
export const DELETE_PERSONNEL = "DELETE_PERSONNEL"

// seller reducer types
export const LOADING_SELLER = "LOADING_SELLER"
export const GET_SELLER_COMPLETED = "GET_SELLER_COMPLETED"
export const CREATE_SELLER = "CREATE_SELLER"
export const UPDATE_SELLER = "UPDATE_SELLER"
export const DELETE_SELLER = "DELETE_SELLER"

// procurement reducer types
export const LOADING_PROCUREMENT = "LOADING_PROCUREMENT"
export const GET_PROCUREMENT = "GET_PROCUREMENT"
export const CREATE_PROCUREMENT = "CREATE_PROCUREMENT"
export const UPDATE_PROCUREMENT = "UPDATE_PROCUREMENT"
export const DELETE_PROCUREMENT = "DELETE_PROCUREMENT"

// allowance reducer types
export const LOADING_ALLOWANCE = "LOADING_ALLOWANCE"
export const GET_ALLOWANCE = "GET_ALLOWANCE"
export const CREATE_ALLOWANCE = "CREATE_ALLOWANCE"
export const UPDATE_ALLOWANCE = "UPDATE_ALLOWANCE"
export const DELETE_ALLOWANCE = "DELETE_ALLOWANCE"

// car reducer types
export const LOADING_CAR = "LOADING_CAR"
export const GET_CAR = "GET_CAR"
export const CREATE_CAR = "CREATE_CAR"
export const UPDATE_CAR = "UPDATE_CAR"
export const DELETE_CAR = "DELETE_CAR"

export const SET_ERRORS = "SET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const GET_SETTING_DATA_COMPLETED = "GET_SETTING_DATA_COMPLETED"
export const LOADING_GET_ALL_SETTING_DATA = "LOADING_GET_ALL_SETTING_DATA"
export const COMPLETED_GET_ALL_SETTING_DATA = "COMPLETED_GET_ALL_SETTING_DATA"
export const REFRESH_ACCESS_TOKEN = "REFRESH_ACCESS_TOKEN"

export const RESET = "RESET"
export const AFTER_UPDATE = "AFTER_UPDATE"

export const SORTED_ITEMS = "SORTED_ITEMS"

export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const LOGGIN_COMPLETED = 'LOGGIN_COMPLETED'
export const LOGGIN_INCOMPLETE = 'LOGGIN_INCOMPLETE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'


export const CLEAR_APP_SETTING_DATA = "CLEAR_APP_SETTING_DATA"




